# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.IntegerField(default=0)),
                ('tweet_text', models.CharField(max_length=140)),
                ('pub_date', models.DateTimeField(verbose_name='date tweeted')),
            ],
        ),
    ]
